CREATE DATABASE GMS;
USE GMS;

CREATE TABLE USERS (
     id int PRIMARY KEY AUTO_INCREMENT,
     usr VARCHAR(255) NOT NULL,
     pwd VARCHAR(255) NOT NULL,
     fst VARCHAR(255) NOT NULL,
     lst VARCHAR(255) NOT NULL
)
                    